services:
  collector:
    build:
      context: app
      target: builder
    container_name: daisi-collector
    restart: "no"
    networks: ["brokers"]
    environment:
      - BROKER_URL=nats://daisi-broker:4222

networks:
  brokers:
    name: brokers
    external: true
