services:
  collector:
    build:
      context: app
      target: builder
    container_name: daisi-collector
    restart: "no"
    networks: ["brokers"]

networks:
  brokers:
    name: brokers
    external: true
